from typing import Any

DEFAULT_CONFIG_DIR = "config"
DEFAULT_CONFIG_FILENAME = "app.yaml"
DEFAULT_CONFIG_TEMPLATE_FILENAME = "default.yaml"
DEFAULT_CONFIG_PATH = f"{DEFAULT_CONFIG_DIR}/{DEFAULT_CONFIG_FILENAME}"
DEFAULT_CONFIG_TEMPLATE_PATH = f"{DEFAULT_CONFIG_DIR}/{DEFAULT_CONFIG_TEMPLATE_FILENAME}"
MODEL_PROFILE_REALTIME = "realtime"
MODEL_PROFILE_OFFLINE = "offline"
MODEL_PROFILE_HYBRID = "hybrid"
MODEL_PROFILE_CUSTOM = "custom"
MODEL_PROFILE_PRESETS: dict[str, dict[str, Any]] = {
    MODEL_PROFILE_REALTIME: {
        "label": "实时",
        "model": "paraformer-zh-streaming",
        "detector_model": "paraformer-zh-streaming",
        "vad_model": "fsmn-vad",
        "punc_model": "ct-punc",
        "disable_vad_model": True,
        "disable_punc_model": True,
    },
    MODEL_PROFILE_OFFLINE: {
        "label": "非实时",
        "model": "paraformer-zh",
        "detector_model": "paraformer-zh-streaming",
        "vad_model": "fsmn-vad",
        "punc_model": "ct-punc",
        "disable_vad_model": False,
        "disable_punc_model": False,
    },
    MODEL_PROFILE_HYBRID: {
        "label": "混合",
        "model": "paraformer-zh",
        "detector_model": "paraformer-zh-streaming",
        "vad_model": "fsmn-vad",
        "punc_model": "ct-punc",
        "disable_vad_model": False,
        "disable_punc_model": False,
    },
}
OVERLAY_PERSIST_KEYS = {
    "x",
    "y",
    "width",
    "height",
    "windowed_mode",
    "stay_on_top",
    "font_size",
    "text_x",
    "text_y",
    "text_width",
    "text_height",
    "bg_width",
    "bg_height",
    "bg_offset_x",
    "bg_offset_y",
}
DEFAULT_CONFIG: dict[str, Any] = {
    "x": 80,
    "y": 80,
    "width": 900,
    "height": 180,
    "lock_size_to_bg": True,
    "windowed_mode": False,
    "stay_on_top": True,
    "opacity": 1.0,
    "font_family": "Microsoft YaHei",
    "font_size": 30,
    "text_color": "#000000",
    "text_x": 120,
    "text_y": 410,
    "text_width": 300,
    "text_height": 180,
    "text_max_lines": 4,
    "text_anim_enable": True,
    "text_anim_duration_ms": 220,
    "text_anim_fade_px": 24,
    "text_anim_offset_y": 10,
    "subtitle_clear_ms": 2200,
    "bg_image": "base.png",
    "bg_width": 0,
    "bg_height": 0,
    "bg_offset_x": 0,
    "bg_offset_y": 0,
    "show_control_panel": False,
    "tray_icon_enable": True,
    "device": None,
    "samplerate": 16000,
    "block_ms": 100,
    "queue_size": 240,
    "energy_threshold": 0.012,
    "silence_ms": 700,
    "partial_interval_ms": 900,
    "max_segment_seconds": 12.0,
    "chunk_size": [0, 10, 5],
    "encoder_chunk_look_back": 4,
    "decoder_chunk_look_back": 1,
    "model_profile": MODEL_PROFILE_REALTIME,
    "model_profile_prompt_on_first_run": True,
    "model_profile_prompted": False,
    "model_download_on_startup": False,
    "model": "paraformer-zh-streaming",
    "detector_model": "paraformer-zh-streaming",
    "vad_model": "fsmn-vad",
    "punc_model": "ct-punc",
    "disable_vad_model": False,
    "disable_punc_model": False,
}
