from typing import Any

DEFAULT_CONFIG_PATH = "config/app.yaml"
OVERLAY_PERSIST_KEYS = {
    "x",
    "y",
    "width",
    "height",
    "windowed_mode",
    "stay_on_top",
    "font_size",
    "text_x",
    "text_y",
    "text_width",
    "text_height",
    "bg_width",
    "bg_height",
    "bg_offset_x",
    "bg_offset_y",
}
DEFAULT_CONFIG: dict[str, Any] = {
    "x": 80,
    "y": 80,
    "width": 900,
    "height": 180,
    "lock_size_to_bg": True,
    "windowed_mode": False,
    "stay_on_top": True,
    "opacity": 1.0,
    "font_family": "Microsoft YaHei",
    "font_size": 30,
    "text_color": "#000000",
    "text_x": 120,
    "text_y": 410,
    "text_width": 300,
    "text_height": 180,
    "text_max_lines": 4,
    "text_anim_enable": True,
    "text_anim_duration_ms": 220,
    "text_anim_fade_px": 24,
    "text_anim_offset_y": 10,
    "subtitle_clear_ms": 2200,
    "bg_image": "base.png",
    "bg_width": 0,
    "bg_height": 0,
    "bg_offset_x": 0,
    "bg_offset_y": 0,
    "show_control_panel": False,
    "tray_icon_enable": True,
    "device": None,
    "samplerate": 16000,
    "block_ms": 100,
    "queue_size": 240,
    "energy_threshold": 0.012,
    "silence_ms": 700,
    "partial_interval_ms": 900,
    "max_segment_seconds": 12.0,
    "chunk_size": [0, 10, 5],
    "encoder_chunk_look_back": 4,
    "decoder_chunk_look_back": 1,
    "model": "paraformer-zh-streaming",
    "vad_model": "fsmn-vad",
    "punc_model": "ct-punc",
    "disable_vad_model": False,
    "disable_punc_model": False,
}
