x: 1494
y: 414
width: 541
height: 648
lock_size_to_bg: true
stay_on_top: true
opacity: 1.0
font_family: Microsoft YaHei
font_size: 20
text_color: '#000000'
text_x: 105
text_y: 459
text_width: 300
text_height: 189
text_max_lines: 4
text_anim_enable: true
text_anim_duration_ms: 220
text_anim_fade_px: 24
text_anim_offset_y: 10
subtitle_clear_ms: 2200
bg_image: base.png
bg_width: 0
bg_height: 0
bg_offset_x: 0
bg_offset_y: 0
show_control_panel: false
tray_icon_enable: true
device: null
samplerate: 16000
block_ms: 100
queue_size: 240
energy_threshold: 0.012
silence_ms: 700
partial_interval_ms: 900
max_segment_seconds: 12.0
chunk_size:
- 0
- 10
- 5
encoder_chunk_look_back: 4
decoder_chunk_look_back: 1
model: paraformer-zh-streaming
vad_model: fsmn-vad
punc_model: ct-punc
disable_vad_model: false
disable_punc_model: false
