MODEL_PROFILE_REALTIME = "realtime"
MODEL_PROFILE_OFFLINE = "offline"
MODEL_PROFILE_HYBRID = "hybrid"
MODEL_PROFILE_CUSTOM = "custom"

MODEL_PROFILE_CHOICES = (
    MODEL_PROFILE_REALTIME,
    MODEL_PROFILE_OFFLINE,
    MODEL_PROFILE_HYBRID,
    MODEL_PROFILE_CUSTOM,
)
